// Define study
const study = lab.util.fromObject({
  "title": "root",
  "type": "lab.flow.Sequence",
  "parameters": {},
  "plugins": [
    {
      "type": "lab.plugins.Metadata",
      "path": undefined
    },
    {
      "type": "lab.plugins.Download",
      "filePrefix": "exp",
      "path": undefined
    }
  ],
  "metadata": {
    "title": "exp",
    "description": "",
    "repository": "",
    "contributors": ""
  },
  "files": {},
  "responses": {},
  "content": [
    {
      "type": "lab.html.Page",
      "items": [
        {
          "required": true,
          "type": "html",
          "content": "\u003Ccenter\u003E\r\n\u003Cdiv class=\"detect_card\" style=\"text-align: left; width: 600px; height: 580px\"\u003E  \r\n\u003Ch3\u003EИнформированное согласие\u003C\u002Fh3\u003E\r\nИсследовательская группа факультета психологии\r\nСанкт-Петербургского государственного университета\r\nприглашает Вас принять участие в психологическом исследовании, \r\nцелью которого является изучение работы когнитивного бессознательного \r\nна материале буквенных рядов. \u003Cp\u003E\u003Cb\u003EПомните, что:\u003C\u002Fb\u003E\u003Cbr\u003E\r\n•\tВаше участие в исследовании исключительно добровольно.\u003Cbr\u003E\r\n•\tВы можете отказаться от участия на любом этапе.\u003C\u002Fp\u003E\r\n\u003Cp\u003EВсе данные, собранные в ходе исследования, будут обработаны обезличенно. \r\nУчастие в исследовании не предполагает получение респондентом \r\nденежной или материальной компенсации или какой-либо другой \r\nпрямой выгоды. Однако информация, полученная в ходе этого исследования, \r\nможет в будущем принести пользу и Вам, и другим людям.\u003C\u002Fp\u003E\r\n\u003Ccenter\u003E\u003Cbutton type=\"submit\" class=\"custom-btn btn-3\"\u003E\u003Cspan\u003EСогласен\u003C\u002Fspan\u003E\u003C\u002Fbutton\u003E\u003C\u002Fcenter\u003E\r\n\u003C\u002Fdiv\u003E\r\n\u003C\u002Fcenter\u003E",
          "name": ""
        }
      ],
      "scrollTop": true,
      "submitButtonText": "Continue →",
      "submitButtonPosition": "hidden",
      "files": {},
      "responses": {
        "": ""
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Информированное согласие"
    },
    {
      "type": "lab.html.Page",
      "items": [
        {
          "required": true,
          "type": "html",
          "content": "\u003Ccenter\u003E\r\n\u003Cdiv class=\"detect_card\" style=\"text-align: left; width: 470px; height:  430px\"\u003E\r\n\r\n\u003Clabel for=\"sex\"\u003EПожалуйста, укажите свой пол:\u003C\u002Flabel\u003E\u003Cbr\u003E\r\n  \u003Cselect class=\"custom-btn custom_select\" name=\"sex\"\u003E\r\n  \u003Coption value=\"m\"\u003Eмужской\u003C\u002Foption\u003E\r\n  \u003Coption value=\"f\" selected\u003Eженский\u003C\u002Foption\u003E\r\n\u003C\u002Fselect\u003E\u003Cbr\u003E\r\n\u003Clabel for=\"sequence\"\u003EНабор стимулов (уточнить у эксперементатора):\u003C\u002Flabel\u003E\u003Cbr\u003E\r\n  \u003Cselect class=\"custom-btn custom_select\" name=\"sequence\"\u003E\r\n  \u003Coption value=\"1\" selected\u003E1\u003C\u002Foption\u003E\r\n  \u003Coption value=\"2\"\u003E2\u003C\u002Foption\u003E\r\n  \u003Coption value=\"3\"\u003E3\u003C\u002Foption\u003E\r\n  \u003Coption value=\"4\"\u003E4\u003C\u002Foption\u003E\r\n\u003C\u002Fselect\u003E\u003Cbr\u003E\r\n\u003Clabel for=\"age\"\u003EВведите возраст:\u003C\u002Flabel\u003E\u003Cbr\u003E\r\n\u003Cinput type=\"number\" id=\"age\" name=\"age\"\r\n       min=\"10\" max=\"90\" required\u003E\u003Cbr\u003E\r\n\u003Clabel for=\"email\"\u003EТакже Вы можете указать свою почту в поле ниже, дабы мы могли связаться с Вами и пригасить на следующий эксперимент.\u003C\u002Flabel\u003E\u003Cp\u003E\r\n\u003Cinput type=\"email\" name=\"email\"\u003E\u003Cp\u003E\r\n\u003Ccenter\u003E\u003Cbutton type=\"submit\" class=\"custom-btn btn-3\"\u003E\u003Cspan\u003EЗакончить\u003C\u002Fspan\u003E\u003C\u002Fbutton\u003E\r\n\u003C\u002Fcenter\u003E\r\n\u003C\u002Fdiv\u003E\r\n\u003C\u002Fcenter\u003E",
          "name": ""
        }
      ],
      "scrollTop": true,
      "submitButtonText": "Continue →",
      "submitButtonPosition": "hidden",
      "files": {},
      "responses": {
        "": ""
      },
      "parameters": {},
      "messageHandlers": {
        "end": function anonymous(
) {
window.sequence = parseInt(this.data.sequence)
window.sex = this.data.sex
window.age = parseInt(this.data.age)
window.email = this.data.email
}
      },
      "title": "Анкета (скрипт)"
    },
    {
      "type": "lab.html.Page",
      "items": [
        {
          "required": true,
          "type": "html",
          "content": "\u003Ccenter\u003E\r\n\u003Cdiv class=\"detect_card\" style=\"text-align: left; width: 600px; height: 520px\"\u003E  \r\nВам будут продемонстрированы 16 буквенных ряда, каждый из которых состоит из 5 букв.\u003Cp\u003E\r\nДемонстрация ряда будет произведена \u003Cb\u003Eочень быстро\u003C\u002Fb\u003E (меньше секунды) и всего \u003Cb\u003Eодин раз.\u003C\u002Fb\u003E\u003Cp\u003E\r\n\u003Cb\u003EВаша задача - постараться запомнить как можно больше буквенных рядов.\u003C\u002Fb\u003E\u003Cp\u003E\r\nПозже Вам потребуется достроить до конца неполные версии продемонстрированных буквенных рядов.\u003Cbr\u003E\u003Cbr\u003E\r\nЕсли Вам понятны условия, нажмите кнопку \u003Cb\u003E\"Начать\"\u003C\u002Fb\u003E.\u003Cp\u003E\r\nПосле нажатия кнопки сконцентрируйтесь на крестике в центре экрана, через 1.5 секунды в этом месте начнется демонстрация буквенных рядов.\u003Cp\u003E\r\n\u003Ccenter\u003E\u003Cbutton type=\"submit\" class=\"custom-btn btn-3\"\u003E\u003Cspan\u003EНачать\u003C\u002Fspan\u003E\u003C\u002Fbutton\u003E\u003C\u002Fcenter\u003E\r\n\u003C\u002Fdiv\u003E\r\n\u003C\u002Fcenter\u003E\r\n",
          "name": ""
        }
      ],
      "scrollTop": true,
      "submitButtonPosition": "hidden",
      "files": {},
      "responses": {
        "": ""
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Инструкция_1"
    },
    {
      "type": "lab.canvas.Screen",
      "content": [
        {
          "type": "i-text",
          "left": 0,
          "top": 0,
          "angle": 0,
          "width": 18.69,
          "height": 36.16,
          "stroke": "#000000",
          "strokeWidth": 1,
          "fill": "#ffffff",
          "text": "+",
          "fontStyle": "normal",
          "fontWeight": "normal",
          "fontSize": 32,
          "fontFamily": "sans-serif",
          "lineHeight": 1.16,
          "textAlign": "center"
        }
      ],
      "viewport": [
        800,
        600
      ],
      "files": {},
      "responses": {
        "": ""
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Фиксационный крест",
      "timeout": "1500"
    },
    {
      "type": "lab.flow.Loop",
      "templateParameters": [
        {
          "seq_1_stimul": "голан",
          "seq_1_type": "invert",
          "seq_1_group": "1",
          "seq_1_ipm": "104,7",
          "seq_2_stimul": "голан",
          "seq_2_type": "invert",
          "seq_2_group": "1",
          "seq_2_ipm": "104,7",
          "seq_3_stimul": "гопас",
          "seq_3_type": "invert",
          "seq_3_group": "2",
          "seq_3_ipm": "62",
          "seq_4_stimul": "гопас",
          "seq_4_type": "invert",
          "seq_4_group": "2",
          "seq_4_ipm": "62"
        },
        {
          "seq_1_stimul": "доран",
          "seq_1_type": "invert",
          "seq_1_group": "1",
          "seq_1_ipm": "385,6",
          "seq_2_stimul": "доран",
          "seq_2_type": "invert",
          "seq_2_group": "1",
          "seq_2_ipm": "385,6",
          "seq_3_stimul": "дотем",
          "seq_3_type": "invert",
          "seq_3_group": "2",
          "seq_3_ipm": "197",
          "seq_4_stimul": "дотем",
          "seq_4_type": "invert",
          "seq_4_group": "2",
          "seq_4_ipm": "197"
        },
        {
          "seq_1_stimul": "жебур",
          "seq_1_type": "invert",
          "seq_1_group": "1",
          "seq_1_ipm": "56,5",
          "seq_2_stimul": "жебур",
          "seq_2_type": "invert",
          "seq_2_group": "1",
          "seq_2_ipm": "56,5",
          "seq_3_stimul": "кижум",
          "seq_3_type": "invert",
          "seq_3_group": "2",
          "seq_3_ipm": "124,7",
          "seq_4_stimul": "кижум",
          "seq_4_type": "invert",
          "seq_4_group": "2",
          "seq_4_ipm": "124,7"
        },
        {
          "seq_1_stimul": "косеп",
          "seq_1_type": "invert",
          "seq_1_group": "1",
          "seq_1_ipm": "55,3",
          "seq_2_stimul": "косеп",
          "seq_2_type": "invert",
          "seq_2_group": "1",
          "seq_2_ipm": "55,3",
          "seq_3_stimul": "мижер",
          "seq_3_type": "invert",
          "seq_3_group": "2",
          "seq_3_ipm": "106,7",
          "seq_4_stimul": "мижер",
          "seq_4_type": "invert",
          "seq_4_group": "2",
          "seq_4_ipm": "106,7"
        },
        {
          "seq_1_stimul": "намор",
          "seq_1_type": "invert",
          "seq_1_group": "1",
          "seq_1_ipm": "157,7",
          "seq_2_stimul": "намор",
          "seq_2_type": "invert",
          "seq_2_group": "1",
          "seq_2_ipm": "157,7",
          "seq_3_stimul": "нозес",
          "seq_3_type": "invert",
          "seq_3_group": "2",
          "seq_3_ipm": "69,2",
          "seq_4_stimul": "нозес",
          "seq_4_type": "invert",
          "seq_4_group": "2",
          "seq_4_ipm": "69,2"
        },
        {
          "seq_1_stimul": "робан",
          "seq_1_type": "invert",
          "seq_1_group": "1",
          "seq_1_ipm": "53,5",
          "seq_2_stimul": "робан",
          "seq_2_type": "invert",
          "seq_2_group": "1",
          "seq_2_ipm": "53,5",
          "seq_3_stimul": "сурив",
          "seq_3_type": "invert",
          "seq_3_group": "2",
          "seq_3_ipm": "106,5",
          "seq_4_stimul": "сурив",
          "seq_4_type": "invert",
          "seq_4_group": "2",
          "seq_4_ipm": "106,5"
        },
        {
          "seq_1_stimul": "тевос",
          "seq_1_type": "invert",
          "seq_1_group": "1",
          "seq_1_ipm": "245,5",
          "seq_2_stimul": "тевос",
          "seq_2_type": "invert",
          "seq_2_group": "1",
          "seq_2_ipm": "245,5",
          "seq_3_stimul": "телиб",
          "seq_3_type": "invert",
          "seq_3_group": "2",
          "seq_3_ipm": "75,4",
          "seq_4_stimul": "телиб",
          "seq_4_type": "invert",
          "seq_4_group": "2",
          "seq_4_ipm": "75,4"
        },
        {
          "seq_1_stimul": "телоп",
          "seq_1_type": "invert",
          "seq_1_group": "1",
          "seq_1_ipm": "66,5",
          "seq_2_stimul": "телоп",
          "seq_2_type": "invert",
          "seq_2_group": "1",
          "seq_2_ipm": "66,5",
          "seq_3_stimul": "товиж",
          "seq_3_type": "invert",
          "seq_3_group": "2",
          "seq_3_ipm": "65,6",
          "seq_4_stimul": "товиж",
          "seq_4_type": "invert",
          "seq_4_group": "2",
          "seq_4_ipm": "65,6"
        },
        {
          "seq_1_stimul": "тепог",
          "seq_1_type": "rand",
          "seq_1_group": "1",
          "seq_1_ipm": "0",
          "seq_2_stimul": "тепог",
          "seq_2_type": "rand",
          "seq_2_group": "1",
          "seq_2_ipm": "0",
          "seq_3_stimul": "рубод",
          "seq_3_type": "rand",
          "seq_3_group": "2",
          "seq_3_ipm": "0",
          "seq_4_stimul": "рубод",
          "seq_4_type": "rand",
          "seq_4_group": "2",
          "seq_4_ipm": "0"
        },
        {
          "seq_1_stimul": "тебор",
          "seq_1_type": "rand",
          "seq_1_group": "1",
          "seq_1_ipm": "0",
          "seq_2_stimul": "тебор",
          "seq_2_type": "rand",
          "seq_2_group": "1",
          "seq_2_ipm": "0",
          "seq_3_stimul": "робет",
          "seq_3_type": "rand",
          "seq_3_group": "2",
          "seq_3_ipm": "0",
          "seq_4_stimul": "робет",
          "seq_4_type": "rand",
          "seq_4_group": "2",
          "seq_4_ipm": "0"
        },
        {
          "seq_1_stimul": "росеп",
          "seq_1_type": "rand",
          "seq_1_group": "1",
          "seq_1_ipm": "0",
          "seq_2_stimul": "росеп",
          "seq_2_type": "rand",
          "seq_2_group": "1",
          "seq_2_ipm": "0",
          "seq_3_stimul": "набеп",
          "seq_3_type": "rand",
          "seq_3_group": "2",
          "seq_3_ipm": "0",
          "seq_4_stimul": "набеп",
          "seq_4_type": "rand",
          "seq_4_group": "2",
          "seq_4_ipm": "0"
        },
        {
          "seq_1_stimul": "песор",
          "seq_1_type": "rand",
          "seq_1_group": "1",
          "seq_1_ipm": "0",
          "seq_2_stimul": "песор",
          "seq_2_type": "rand",
          "seq_2_group": "1",
          "seq_2_ipm": "0",
          "seq_3_stimul": "мизес",
          "seq_3_type": "rand",
          "seq_3_group": "2",
          "seq_3_ipm": "0",
          "seq_4_stimul": "мизес",
          "seq_4_type": "rand",
          "seq_4_group": "2",
          "seq_4_ipm": "0"
        },
        {
          "seq_1_stimul": "нарес",
          "seq_1_type": "rand",
          "seq_1_group": "1",
          "seq_1_ipm": "0",
          "seq_2_stimul": "нарес",
          "seq_2_type": "rand",
          "seq_2_group": "1",
          "seq_2_ipm": "0",
          "seq_3_stimul": "мелоп",
          "seq_3_type": "rand",
          "seq_3_group": "2",
          "seq_3_ipm": "0",
          "seq_4_stimul": "мелоп",
          "seq_4_type": "rand",
          "seq_4_group": "2",
          "seq_4_ipm": "0"
        },
        {
          "seq_1_stimul": "жебик",
          "seq_1_type": "rand",
          "seq_1_group": "1",
          "seq_1_ipm": "0",
          "seq_2_stimul": "жебик",
          "seq_2_type": "rand",
          "seq_2_group": "1",
          "seq_2_ipm": "0",
          "seq_3_stimul": "живум",
          "seq_3_type": "rand",
          "seq_3_group": "2",
          "seq_3_ipm": "0",
          "seq_4_stimul": "живум",
          "seq_4_type": "rand",
          "seq_4_group": "2",
          "seq_4_ipm": "0"
        },
        {
          "seq_1_stimul": "доман",
          "seq_1_type": "rand",
          "seq_1_group": "1",
          "seq_1_ipm": "0",
          "seq_2_stimul": "доман",
          "seq_2_type": "rand",
          "seq_2_group": "1",
          "seq_2_ipm": "0",
          "seq_3_stimul": "дотан",
          "seq_3_type": "rand",
          "seq_3_group": "2",
          "seq_3_ipm": "0",
          "seq_4_stimul": "дотан",
          "seq_4_type": "rand",
          "seq_4_group": "2",
          "seq_4_ipm": "0"
        },
        {
          "seq_1_stimul": "голиж",
          "seq_1_type": "rand",
          "seq_1_group": "1",
          "seq_1_ipm": "0",
          "seq_2_stimul": "голиж",
          "seq_2_type": "rand",
          "seq_2_group": "1",
          "seq_2_ipm": "0",
          "seq_3_stimul": "гопет",
          "seq_3_type": "rand",
          "seq_3_group": "2",
          "seq_3_ipm": "0",
          "seq_4_stimul": "гопет",
          "seq_4_type": "rand",
          "seq_4_group": "2",
          "seq_4_ipm": "0"
        }
      ],
      "sample": {
        "mode": "draw-shuffle",
        "n": ""
      },
      "files": {},
      "responses": {
        "": ""
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Запоминание",
      "indexParameter": "counter",
      "tardy": true,
      "shuffleGroups": [],
      "template": {
        "type": "lab.flow.Sequence",
        "files": {},
        "responses": {
          "": ""
        },
        "parameters": {},
        "messageHandlers": {},
        "title": "Последовательность",
        "content": [
          {
            "type": "lab.html.Page",
            "items": [
              {
                "type": "text",
                "content": "\u003Ccenter style=\"color: white; font-size: 24px;\"\u003E${ parameters['seq_' + sequence + '_stimul'] }\u003C\u002Fcenter\u003E\n"
              }
            ],
            "scrollTop": true,
            "submitButtonText": "Continue →",
            "submitButtonPosition": "hidden",
            "files": {},
            "responses": {
              "": ""
            },
            "parameters": {},
            "messageHandlers": {},
            "title": "стимулы",
            "timeout": "380"
          },
          {
            "type": "lab.canvas.Screen",
            "content": [],
            "viewport": [
              800,
              600
            ],
            "files": {},
            "responses": {
              "": ""
            },
            "parameters": {},
            "messageHandlers": {},
            "title": "задержка",
            "timeout": "36"
          }
        ]
      }
    },
    {
      "type": "lab.html.Page",
      "items": [
        {
          "required": true,
          "type": "html",
          "content": "\u003Ccenter\u003E\r\n\u003Cdiv class=\"detect_card\" style=\"text-align: left; width: 526px; height:  415px\"\u003E\r\nДалее Вам будет последовательно предъявлено 40 слов с пропущенными буквами.\u003Cp\u003E\r\nВам надо будет дополнить слоги двумя пропущенными буквами, так, чтобы они образовывали слово, которое вы видели на первом этапе. \r\nНапример,\u003C\u002Fp\u003E\u003Cp\u003E Вам предъявляться слово РОГ__, в котором пропущенны две последние буквы и дано три варианта на выбор: \u003Cbr\u003E1) БА, \u003Cbr\u003E2) РА, \u003Cbr\u003E3) НА. \u003C\u002Fp\u003E \u003Cp\u003EВам необходимо \u003Cb style=\"color: rgba(69, 192, 250, 1)\"\u003E выбрать один из трёх вариантов \u003C\u002Fb\u003E и нажать кнопку \"Ответить\". \r\n\u003C\u002Fp\u003E\r\n\u003Ccenter\u003E\r\n  \u003Cbr\u003E\r\n\u003Ccenter\u003E\u003Cbutton type=\"submit\" class=\"custom-btn btn-3\"\u003E\u003Cspan\u003EНачать\u003C\u002Fspan\u003E\u003C\u002Fbutton\u003E\u003C\u002Fcenter\u003E\r\n\u003C\u002Fcenter\u003E\r\n\u003C\u002Fdiv\u003E\r\n\u003C\u002Fcenter\u003E",
          "name": ""
        }
      ],
      "scrollTop": true,
      "submitButtonText": "Continue →",
      "submitButtonPosition": "hidden",
      "files": {},
      "responses": {
        "": ""
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Инструкция_2"
    },
    {
      "type": "lab.flow.Loop",
      "templateParameters": [
        {
          "seq_4_stimul": "нозес",
          "seq_3_stimul": "телиб",
          "seq_2_stimul": "робан",
          "seq_1_stimul": "жебур",
          "ID": "1",
          "seq_1_base": "жеб",
          "seq_1_c_inv": "ур",
          "seq_1_c_unmean": "ик",
          "seq_1_c_dis1": "уг",
          "seq_1_c_dis2": "ин",
          "seq_1_ipm": "565",
          "seq_1_answers_seq": "423",
          "seq_2_base": "роб",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "ет",
          "seq_2_c_dis1": "аг",
          "seq_2_c_dis2": "ен",
          "seq_2_ipm": "535",
          "seq_2_answers_seq": "423",
          "seq_3_base": "тел",
          "seq_3_c_inv": "иб",
          "seq_3_c_unmean": "ус",
          "seq_3_c_dis1": "ип",
          "seq_3_c_dis2": "уп",
          "seq_3_ipm": "754",
          "seq_3_answers_seq": "134",
          "seq_4_base": "ноз",
          "seq_4_c_inv": "ес",
          "seq_4_c_unmean": "ет",
          "seq_4_c_dis1": "ем",
          "seq_4_c_dis2": "ек",
          "seq_4_ipm": "692",
          "seq_4_answers_seq": "423"
        },
        {
          "seq_4_stimul": "дотем",
          "seq_3_stimul": "сурив",
          "seq_2_stimul": "тевос",
          "seq_1_stimul": "робан",
          "ID": "2",
          "seq_1_base": "роб",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "ет",
          "seq_1_c_dis1": "аг",
          "seq_1_c_dis2": "ен",
          "seq_1_ipm": "535",
          "seq_1_answers_seq": "234",
          "seq_2_base": "тев",
          "seq_2_c_inv": "ос",
          "seq_2_c_unmean": "ор",
          "seq_2_c_dis1": "ог",
          "seq_2_c_dis2": "ол",
          "seq_2_ipm": "2455",
          "seq_2_answers_seq": "123",
          "seq_3_base": "сур",
          "seq_3_c_inv": "ив",
          "seq_3_c_unmean": "оп",
          "seq_3_c_dis1": "ил",
          "seq_3_c_dis2": "од",
          "seq_3_ipm": "1065",
          "seq_3_answers_seq": "234",
          "seq_4_base": "дот",
          "seq_4_c_inv": "ем",
          "seq_4_c_unmean": "ан",
          "seq_4_c_dis1": "ин",
          "seq_4_c_dis2": "ам",
          "seq_4_ipm": "197",
          "seq_4_answers_seq": "234"
        },
        {
          "seq_4_stimul": "товиж",
          "seq_3_stimul": "товиж",
          "seq_2_stimul": "голан",
          "seq_1_stimul": "косеп",
          "ID": "3",
          "seq_1_base": "кос",
          "seq_1_c_inv": "еп",
          "seq_1_c_unmean": "ед",
          "seq_1_c_dis1": "ад",
          "seq_1_c_dis2": "ен",
          "seq_1_ipm": "553",
          "seq_1_answers_seq": "123",
          "seq_2_base": "гол",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "иж",
          "seq_2_c_dis1": "ар",
          "seq_2_c_dis2": "ин",
          "seq_2_ipm": "1047",
          "seq_2_answers_seq": "234",
          "seq_3_base": "тов",
          "seq_3_c_inv": "иж",
          "seq_3_c_unmean": "ик",
          "seq_3_c_dis1": "ин",
          "seq_3_c_dis2": "иг",
          "seq_3_ipm": "656",
          "seq_3_answers_seq": "123",
          "seq_4_base": "тов",
          "seq_4_c_inv": "иж",
          "seq_4_c_unmean": "ик",
          "seq_4_c_dis1": "ин",
          "seq_4_c_dis2": "иг",
          "seq_4_ipm": "656",
          "seq_4_answers_seq": "123"
        },
        {
          "seq_4_stimul": "мижер",
          "seq_3_stimul": "дотем",
          "seq_2_stimul": "телоп",
          "seq_1_stimul": "тевос",
          "ID": "4",
          "seq_1_base": "тев",
          "seq_1_c_inv": "ос",
          "seq_1_c_unmean": "ор",
          "seq_1_c_dis1": "ог",
          "seq_1_c_dis2": "ол",
          "seq_1_ipm": "2455",
          "seq_1_answers_seq": "123",
          "seq_2_base": "тел",
          "seq_2_c_inv": "оп",
          "seq_2_c_unmean": "ун",
          "seq_2_c_dis1": "од",
          "seq_2_c_dis2": "уд",
          "seq_2_ipm": "665",
          "seq_2_answers_seq": "234",
          "seq_3_base": "дот",
          "seq_3_c_inv": "ем",
          "seq_3_c_unmean": "ан",
          "seq_3_c_dis1": "ин",
          "seq_3_c_dis2": "ам",
          "seq_3_ipm": "197",
          "seq_3_answers_seq": "123",
          "seq_4_base": "миж",
          "seq_4_c_inv": "ер",
          "seq_4_c_unmean": "ед",
          "seq_4_c_dis1": "ен",
          "seq_4_c_dis2": "ет",
          "seq_4_ipm": "1067",
          "seq_4_answers_seq": "124"
        },
        {
          "seq_4_stimul": "кижум",
          "seq_3_stimul": "гопас",
          "seq_2_stimul": "косеп",
          "seq_1_stimul": "голан",
          "ID": "5",
          "seq_1_base": "гол",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "иж",
          "seq_1_c_dis1": "ар",
          "seq_1_c_dis2": "ин",
          "seq_1_ipm": "1047",
          "seq_1_answers_seq": "234",
          "seq_2_base": "кос",
          "seq_2_c_inv": "еп",
          "seq_2_c_unmean": "ед",
          "seq_2_c_dis1": "ад",
          "seq_2_c_dis2": "ен",
          "seq_2_ipm": "553",
          "seq_2_answers_seq": "423",
          "seq_3_base": "гоп",
          "seq_3_c_inv": "ас",
          "seq_3_c_unmean": "ет",
          "seq_3_c_dis1": "ал",
          "seq_3_c_dis2": "ед",
          "seq_3_ipm": "62",
          "seq_3_answers_seq": "234",
          "seq_4_base": "киж",
          "seq_4_c_inv": "ум",
          "seq_4_c_unmean": "ас",
          "seq_4_c_dis1": "ан",
          "seq_4_c_dis2": "ут",
          "seq_4_ipm": "1247",
          "seq_4_answers_seq": "134"
        },
        {
          "seq_4_stimul": "телиб",
          "seq_3_stimul": "кижум",
          "seq_2_stimul": "жебур",
          "seq_1_stimul": "доран",
          "ID": "6",
          "seq_1_base": "дор",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "ем",
          "seq_1_c_dis1": "ен",
          "seq_1_c_dis2": "аг",
          "seq_1_ipm": "3856",
          "seq_1_answers_seq": "234",
          "seq_2_base": "жеб",
          "seq_2_c_inv": "ур",
          "seq_2_c_unmean": "ик",
          "seq_2_c_dis1": "уг",
          "seq_2_c_dis2": "ин",
          "seq_2_ipm": "565",
          "seq_2_answers_seq": "234",
          "seq_3_base": "киж",
          "seq_3_c_inv": "ум",
          "seq_3_c_unmean": "ас",
          "seq_3_c_dis1": "ан",
          "seq_3_c_dis2": "ут",
          "seq_3_ipm": "1247",
          "seq_3_answers_seq": "234",
          "seq_4_base": "тел",
          "seq_4_c_inv": "иб",
          "seq_4_c_unmean": "ус",
          "seq_4_c_dis1": "ип",
          "seq_4_c_dis2": "уп",
          "seq_4_ipm": "754",
          "seq_4_answers_seq": "234"
        },
        {
          "seq_4_stimul": "сурив",
          "seq_3_stimul": "мижер",
          "seq_2_stimul": "намор",
          "seq_1_stimul": "телоп",
          "ID": "7",
          "seq_1_base": "тел",
          "seq_1_c_inv": "оп",
          "seq_1_c_unmean": "ун",
          "seq_1_c_dis1": "од",
          "seq_1_c_dis2": "уд",
          "seq_1_ipm": "665",
          "seq_1_answers_seq": "423",
          "seq_2_base": "нам",
          "seq_2_c_inv": "ор",
          "seq_2_c_unmean": "од",
          "seq_2_c_dis1": "от",
          "seq_2_c_dis2": "ог",
          "seq_2_ipm": "1577",
          "seq_2_answers_seq": "123",
          "seq_3_base": "миж",
          "seq_3_c_inv": "ер",
          "seq_3_c_unmean": "ед",
          "seq_3_c_dis1": "ен",
          "seq_3_c_dis2": "ет",
          "seq_3_ipm": "1067",
          "seq_3_answers_seq": "123",
          "seq_4_base": "сур",
          "seq_4_c_inv": "ив",
          "seq_4_c_unmean": "оп",
          "seq_4_c_dis1": "ил",
          "seq_4_c_dis2": "од",
          "seq_4_ipm": "1065",
          "seq_4_answers_seq": "123"
        },
        {
          "seq_4_stimul": "гопас",
          "seq_3_stimul": "нозес",
          "seq_2_stimul": "доран",
          "seq_1_stimul": "намор",
          "ID": "8",
          "seq_1_base": "нам",
          "seq_1_c_inv": "ор",
          "seq_1_c_unmean": "од",
          "seq_1_c_dis1": "от",
          "seq_1_c_dis2": "ог",
          "seq_1_ipm": "1577",
          "seq_1_answers_seq": "124",
          "seq_2_base": "дор",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "ем",
          "seq_2_c_dis1": "ен",
          "seq_2_c_dis2": "аг",
          "seq_2_ipm": "3856",
          "seq_2_answers_seq": "423",
          "seq_3_base": "ноз",
          "seq_3_c_inv": "ес",
          "seq_3_c_unmean": "ет",
          "seq_3_c_dis1": "ем",
          "seq_3_c_dis2": "ек",
          "seq_3_ipm": "692",
          "seq_3_answers_seq": "124",
          "seq_4_base": "гоп",
          "seq_4_c_inv": "ас",
          "seq_4_c_unmean": "ет",
          "seq_4_c_dis1": "ал",
          "seq_4_c_dis2": "ед",
          "seq_4_ipm": "62",
          "seq_4_answers_seq": "123"
        },
        {
          "seq_4_stimul": "телиб",
          "seq_3_stimul": "нозес",
          "seq_2_stimul": "жебур",
          "seq_1_stimul": "робан",
          "ID": "9",
          "seq_1_base": "роб",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "ет",
          "seq_1_c_dis1": "аг",
          "seq_1_c_dis2": "ен",
          "seq_1_ipm": "535",
          "seq_1_answers_seq": "134",
          "seq_2_base": "жеб",
          "seq_2_c_inv": "ур",
          "seq_2_c_unmean": "ик",
          "seq_2_c_dis1": "уг",
          "seq_2_c_dis2": "ин",
          "seq_2_ipm": "565",
          "seq_2_answers_seq": "124",
          "seq_3_base": "ноз",
          "seq_3_c_inv": "ес",
          "seq_3_c_unmean": "ет",
          "seq_3_c_dis1": "ем",
          "seq_3_c_dis2": "ек",
          "seq_3_ipm": "692",
          "seq_3_answers_seq": "423",
          "seq_4_base": "тел",
          "seq_4_c_inv": "иб",
          "seq_4_c_unmean": "ус",
          "seq_4_c_dis1": "ип",
          "seq_4_c_dis2": "уп",
          "seq_4_ipm": "754",
          "seq_4_answers_seq": "124"
        },
        {
          "seq_4_stimul": "сурив",
          "seq_3_stimul": "дотем",
          "seq_2_stimul": "робан",
          "seq_1_stimul": "тевос",
          "ID": "10",
          "seq_1_base": "тев",
          "seq_1_c_inv": "ос",
          "seq_1_c_unmean": "ор",
          "seq_1_c_dis1": "ог",
          "seq_1_c_dis2": "ол",
          "seq_1_ipm": "2455",
          "seq_1_answers_seq": "234",
          "seq_2_base": "роб",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "ет",
          "seq_2_c_dis1": "аг",
          "seq_2_c_dis2": "ен",
          "seq_2_ipm": "535",
          "seq_2_answers_seq": "124",
          "seq_3_base": "дот",
          "seq_3_c_inv": "ем",
          "seq_3_c_unmean": "ан",
          "seq_3_c_dis1": "ин",
          "seq_3_c_dis2": "ам",
          "seq_3_ipm": "197",
          "seq_3_answers_seq": "124",
          "seq_4_base": "сур",
          "seq_4_c_inv": "ив",
          "seq_4_c_unmean": "оп",
          "seq_4_c_dis1": "ил",
          "seq_4_c_dis2": "од",
          "seq_4_ipm": "1065",
          "seq_4_answers_seq": "134"
        },
        {
          "seq_4_stimul": "товиж",
          "seq_3_stimul": "товиж",
          "seq_2_stimul": "косеп",
          "seq_1_stimul": "голан",
          "ID": "11",
          "seq_1_base": "гол",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "иж",
          "seq_1_c_dis1": "ар",
          "seq_1_c_dis2": "ин",
          "seq_1_ipm": "1047",
          "seq_1_answers_seq": "124",
          "seq_2_base": "кос",
          "seq_2_c_inv": "еп",
          "seq_2_c_unmean": "ед",
          "seq_2_c_dis1": "ад",
          "seq_2_c_dis2": "ен",
          "seq_2_ipm": "553",
          "seq_2_answers_seq": "234",
          "seq_3_base": "тов",
          "seq_3_c_inv": "иж",
          "seq_3_c_unmean": "ик",
          "seq_3_c_dis1": "ин",
          "seq_3_c_dis2": "иг",
          "seq_3_ipm": "656",
          "seq_3_answers_seq": "124",
          "seq_4_base": "тов",
          "seq_4_c_inv": "иж",
          "seq_4_c_unmean": "ик",
          "seq_4_c_dis1": "ин",
          "seq_4_c_dis2": "иг",
          "seq_4_ipm": "656",
          "seq_4_answers_seq": "423"
        },
        {
          "seq_4_stimul": "дотем",
          "seq_3_stimul": "мижер",
          "seq_2_stimul": "тевос",
          "seq_1_stimul": "телоп",
          "ID": "12",
          "seq_1_base": "тел",
          "seq_1_c_inv": "оп",
          "seq_1_c_unmean": "ун",
          "seq_1_c_dis1": "од",
          "seq_1_c_dis2": "уд",
          "seq_1_ipm": "665",
          "seq_1_answers_seq": "234",
          "seq_2_base": "тев",
          "seq_2_c_inv": "ос",
          "seq_2_c_unmean": "ор",
          "seq_2_c_dis1": "ог",
          "seq_2_c_dis2": "ол",
          "seq_2_ipm": "2455",
          "seq_2_answers_seq": "134",
          "seq_3_base": "миж",
          "seq_3_c_inv": "ер",
          "seq_3_c_unmean": "ед",
          "seq_3_c_dis1": "ен",
          "seq_3_c_dis2": "ет",
          "seq_3_ipm": "1067",
          "seq_3_answers_seq": "124",
          "seq_4_base": "дот",
          "seq_4_c_inv": "ем",
          "seq_4_c_unmean": "ан",
          "seq_4_c_dis1": "ин",
          "seq_4_c_dis2": "ам",
          "seq_4_ipm": "197",
          "seq_4_answers_seq": "134"
        },
        {
          "seq_4_stimul": "гопас",
          "seq_3_stimul": "кижум",
          "seq_2_stimul": "голан",
          "seq_1_stimul": "косеп",
          "ID": "13",
          "seq_1_base": "кос",
          "seq_1_c_inv": "еп",
          "seq_1_c_unmean": "ед",
          "seq_1_c_dis1": "ад",
          "seq_1_c_dis2": "ен",
          "seq_1_ipm": "553",
          "seq_1_answers_seq": "234",
          "seq_2_base": "гол",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "иж",
          "seq_2_c_dis1": "ар",
          "seq_2_c_dis2": "ин",
          "seq_2_ipm": "1047",
          "seq_2_answers_seq": "123",
          "seq_3_base": "киж",
          "seq_3_c_inv": "ум",
          "seq_3_c_unmean": "ас",
          "seq_3_c_dis1": "ан",
          "seq_3_c_dis2": "ут",
          "seq_3_ipm": "1247",
          "seq_3_answers_seq": "123",
          "seq_4_base": "гоп",
          "seq_4_c_inv": "ас",
          "seq_4_c_unmean": "ет",
          "seq_4_c_dis1": "ал",
          "seq_4_c_dis2": "ед",
          "seq_4_ipm": "62",
          "seq_4_answers_seq": "234"
        },
        {
          "seq_4_stimul": "кижум",
          "seq_3_stimul": "телиб",
          "seq_2_stimul": "доран",
          "seq_1_stimul": "жебур",
          "ID": "14",
          "seq_1_base": "жеб",
          "seq_1_c_inv": "ур",
          "seq_1_c_unmean": "ик",
          "seq_1_c_dis1": "уг",
          "seq_1_c_dis2": "ин",
          "seq_1_ipm": "565",
          "seq_1_answers_seq": "234",
          "seq_2_base": "дор",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "ем",
          "seq_2_c_dis1": "ен",
          "seq_2_c_dis2": "аг",
          "seq_2_ipm": "3856",
          "seq_2_answers_seq": "123",
          "seq_3_base": "тел",
          "seq_3_c_inv": "иб",
          "seq_3_c_unmean": "ус",
          "seq_3_c_dis1": "ип",
          "seq_3_c_dis2": "уп",
          "seq_3_ipm": "754",
          "seq_3_answers_seq": "234",
          "seq_4_base": "киж",
          "seq_4_c_inv": "ум",
          "seq_4_c_unmean": "ас",
          "seq_4_c_dis1": "ан",
          "seq_4_c_dis2": "ут",
          "seq_4_ipm": "1247",
          "seq_4_answers_seq": "423"
        },
        {
          "seq_4_stimul": "мижер",
          "seq_3_stimul": "сурив",
          "seq_2_stimul": "телоп",
          "seq_1_stimul": "намор",
          "ID": "15",
          "seq_1_base": "нам",
          "seq_1_c_inv": "ор",
          "seq_1_c_unmean": "од",
          "seq_1_c_dis1": "от",
          "seq_1_c_dis2": "ог",
          "seq_1_ipm": "1577",
          "seq_1_answers_seq": "234",
          "seq_2_base": "тел",
          "seq_2_c_inv": "оп",
          "seq_2_c_unmean": "ун",
          "seq_2_c_dis1": "од",
          "seq_2_c_dis2": "уд",
          "seq_2_ipm": "665",
          "seq_2_answers_seq": "124",
          "seq_3_base": "сур",
          "seq_3_c_inv": "ив",
          "seq_3_c_unmean": "оп",
          "seq_3_c_dis1": "ил",
          "seq_3_c_dis2": "од",
          "seq_3_ipm": "1065",
          "seq_3_answers_seq": "123",
          "seq_4_base": "миж",
          "seq_4_c_inv": "ер",
          "seq_4_c_unmean": "ед",
          "seq_4_c_dis1": "ен",
          "seq_4_c_dis2": "ет",
          "seq_4_ipm": "1067",
          "seq_4_answers_seq": "423"
        },
        {
          "seq_4_stimul": "нозес",
          "seq_3_stimul": "гопас",
          "seq_2_stimul": "намор",
          "seq_1_stimul": "доран",
          "ID": "16",
          "seq_1_base": "дор",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "ем",
          "seq_1_c_dis1": "ен",
          "seq_1_c_dis2": "аг",
          "seq_1_ipm": "3856",
          "seq_1_answers_seq": "124",
          "seq_2_base": "нам",
          "seq_2_c_inv": "ор",
          "seq_2_c_unmean": "од",
          "seq_2_c_dis1": "от",
          "seq_2_c_dis2": "ог",
          "seq_2_ipm": "1577",
          "seq_2_answers_seq": "423",
          "seq_3_base": "гоп",
          "seq_3_c_inv": "ас",
          "seq_3_c_unmean": "ет",
          "seq_3_c_dis1": "ал",
          "seq_3_c_dis2": "ед",
          "seq_3_ipm": "62",
          "seq_3_answers_seq": "123",
          "seq_4_base": "ноз",
          "seq_4_c_inv": "ес",
          "seq_4_c_unmean": "ет",
          "seq_4_c_dis1": "ем",
          "seq_4_c_dis2": "ек",
          "seq_4_ipm": "692",
          "seq_4_answers_seq": "123"
        },
        {
          "seq_4_stimul": "мижер",
          "seq_3_stimul": "нозес",
          "seq_2_stimul": "косеп",
          "seq_1_stimul": "намор",
          "ID": "17",
          "seq_1_base": "нам",
          "seq_1_c_inv": "ор",
          "seq_1_c_unmean": "од",
          "seq_1_c_dis1": "от",
          "seq_1_c_dis2": "ог",
          "seq_1_ipm": "1577",
          "seq_1_answers_seq": "134",
          "seq_2_base": "кос",
          "seq_2_c_inv": "еп",
          "seq_2_c_unmean": "ед",
          "seq_2_c_dis1": "ад",
          "seq_2_c_dis2": "ен",
          "seq_2_ipm": "553",
          "seq_2_answers_seq": "134",
          "seq_3_base": "ноз",
          "seq_3_c_inv": "ес",
          "seq_3_c_unmean": "ет",
          "seq_3_c_dis1": "ем",
          "seq_3_c_dis2": "ек",
          "seq_3_ipm": "692",
          "seq_3_answers_seq": "123",
          "seq_4_base": "миж",
          "seq_4_c_inv": "ер",
          "seq_4_c_unmean": "ед",
          "seq_4_c_dis1": "ен",
          "seq_4_c_dis2": "ет",
          "seq_4_ipm": "1067",
          "seq_4_answers_seq": "123"
        },
        {
          "seq_4_stimul": "телиб",
          "seq_3_stimul": "сурив",
          "seq_2_stimul": "телоп",
          "seq_1_stimul": "робан",
          "ID": "18",
          "seq_1_base": "роб",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "ет",
          "seq_1_c_dis1": "аг",
          "seq_1_c_dis2": "ен",
          "seq_1_ipm": "535",
          "seq_1_answers_seq": "124",
          "seq_2_base": "тел",
          "seq_2_c_inv": "оп",
          "seq_2_c_unmean": "ун",
          "seq_2_c_dis1": "од",
          "seq_2_c_dis2": "уд",
          "seq_2_ipm": "665",
          "seq_2_answers_seq": "134",
          "seq_3_base": "сур",
          "seq_3_c_inv": "ив",
          "seq_3_c_unmean": "оп",
          "seq_3_c_dis1": "ил",
          "seq_3_c_dis2": "од",
          "seq_3_ipm": "1065",
          "seq_3_answers_seq": "124",
          "seq_4_base": "тел",
          "seq_4_c_inv": "иб",
          "seq_4_c_unmean": "ус",
          "seq_4_c_dis1": "ип",
          "seq_4_c_dis2": "уп",
          "seq_4_ipm": "754",
          "seq_4_answers_seq": "123"
        },
        {
          "seq_4_stimul": "товиж",
          "seq_3_stimul": "дотем",
          "seq_2_stimul": "доран",
          "seq_1_stimul": "телоп",
          "ID": "19",
          "seq_1_base": "тел",
          "seq_1_c_inv": "оп",
          "seq_1_c_unmean": "ун",
          "seq_1_c_dis1": "од",
          "seq_1_c_dis2": "уд",
          "seq_1_ipm": "665",
          "seq_1_answers_seq": "123",
          "seq_2_base": "дор",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "ем",
          "seq_2_c_dis1": "ен",
          "seq_2_c_dis2": "аг",
          "seq_2_ipm": "3856",
          "seq_2_answers_seq": "234",
          "seq_3_base": "дот",
          "seq_3_c_inv": "ем",
          "seq_3_c_unmean": "ан",
          "seq_3_c_dis1": "ин",
          "seq_3_c_dis2": "ам",
          "seq_3_ipm": "197",
          "seq_3_answers_seq": "423",
          "seq_4_base": "тов",
          "seq_4_c_inv": "иж",
          "seq_4_c_unmean": "ик",
          "seq_4_c_dis1": "ин",
          "seq_4_c_dis2": "иг",
          "seq_4_ipm": "656",
          "seq_4_answers_seq": "134"
        },
        {
          "seq_4_stimul": "гопас",
          "seq_3_stimul": "кижум",
          "seq_2_stimul": "голан",
          "seq_1_stimul": "косеп",
          "ID": "20",
          "seq_1_base": "кос",
          "seq_1_c_inv": "еп",
          "seq_1_c_unmean": "ед",
          "seq_1_c_dis1": "ад",
          "seq_1_c_dis2": "ен",
          "seq_1_ipm": "553",
          "seq_1_answers_seq": "124",
          "seq_2_base": "гол",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "иж",
          "seq_2_c_dis1": "ар",
          "seq_2_c_dis2": "ин",
          "seq_2_ipm": "1047",
          "seq_2_answers_seq": "124",
          "seq_3_base": "киж",
          "seq_3_c_inv": "ум",
          "seq_3_c_unmean": "ас",
          "seq_3_c_dis1": "ан",
          "seq_3_c_dis2": "ут",
          "seq_3_ipm": "1247",
          "seq_3_answers_seq": "134",
          "seq_4_base": "гоп",
          "seq_4_c_inv": "ас",
          "seq_4_c_unmean": "ет",
          "seq_4_c_dis1": "ал",
          "seq_4_c_dis2": "ед",
          "seq_4_ipm": "62",
          "seq_4_answers_seq": "134"
        },
        {
          "seq_4_stimul": "дотем",
          "seq_3_stimul": "мижер",
          "seq_2_stimul": "тевос",
          "seq_1_stimul": "доран",
          "ID": "21",
          "seq_1_base": "дор",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "ем",
          "seq_1_c_dis1": "ен",
          "seq_1_c_dis2": "аг",
          "seq_1_ipm": "3856",
          "seq_1_answers_seq": "134",
          "seq_2_base": "тев",
          "seq_2_c_inv": "ос",
          "seq_2_c_unmean": "ор",
          "seq_2_c_dis1": "ог",
          "seq_2_c_dis2": "ол",
          "seq_2_ipm": "2455",
          "seq_2_answers_seq": "124",
          "seq_3_base": "миж",
          "seq_3_c_inv": "ер",
          "seq_3_c_unmean": "ед",
          "seq_3_c_dis1": "ен",
          "seq_3_c_dis2": "ет",
          "seq_3_ipm": "1067",
          "seq_3_answers_seq": "234",
          "seq_4_base": "дот",
          "seq_4_c_inv": "ем",
          "seq_4_c_unmean": "ан",
          "seq_4_c_dis1": "ин",
          "seq_4_c_dis2": "ам",
          "seq_4_ipm": "197",
          "seq_4_answers_seq": "423"
        },
        {
          "seq_4_stimul": "нозес",
          "seq_3_stimul": "телиб",
          "seq_2_stimul": "робан",
          "seq_1_stimul": "голан",
          "ID": "22",
          "seq_1_base": "гол",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "иж",
          "seq_1_c_dis1": "ар",
          "seq_1_c_dis2": "ин",
          "seq_1_ipm": "1047",
          "seq_1_answers_seq": "123",
          "seq_2_base": "роб",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "ет",
          "seq_2_c_dis1": "аг",
          "seq_2_c_dis2": "ен",
          "seq_2_ipm": "535",
          "seq_2_answers_seq": "123",
          "seq_3_base": "тел",
          "seq_3_c_inv": "иб",
          "seq_3_c_unmean": "ус",
          "seq_3_c_dis1": "ип",
          "seq_3_c_dis2": "уп",
          "seq_3_ipm": "754",
          "seq_3_answers_seq": "124",
          "seq_4_base": "ноз",
          "seq_4_c_inv": "ес",
          "seq_4_c_unmean": "ет",
          "seq_4_c_dis1": "ем",
          "seq_4_c_dis2": "ек",
          "seq_4_ipm": "692",
          "seq_4_answers_seq": "234"
        },
        {
          "seq_4_stimul": "сурив",
          "seq_3_stimul": "гопас",
          "seq_2_stimul": "жебур",
          "seq_1_stimul": "тевос",
          "ID": "23",
          "seq_1_base": "тев",
          "seq_1_c_inv": "ос",
          "seq_1_c_unmean": "ор",
          "seq_1_c_dis1": "ог",
          "seq_1_c_dis2": "ол",
          "seq_1_ipm": "2455",
          "seq_1_answers_seq": "423",
          "seq_2_base": "жеб",
          "seq_2_c_inv": "ур",
          "seq_2_c_unmean": "ик",
          "seq_2_c_dis1": "уг",
          "seq_2_c_dis2": "ин",
          "seq_2_ipm": "565",
          "seq_2_answers_seq": "123",
          "seq_3_base": "гоп",
          "seq_3_c_inv": "ас",
          "seq_3_c_unmean": "ет",
          "seq_3_c_dis1": "ал",
          "seq_3_c_dis2": "ед",
          "seq_3_ipm": "62",
          "seq_3_answers_seq": "423",
          "seq_4_base": "сур",
          "seq_4_c_inv": "ив",
          "seq_4_c_unmean": "оп",
          "seq_4_c_dis1": "ил",
          "seq_4_c_dis2": "од",
          "seq_4_ipm": "1065",
          "seq_4_answers_seq": "124"
        },
        {
          "seq_4_stimul": "кижум",
          "seq_3_stimul": "товиж",
          "seq_2_stimul": "намор",
          "seq_1_stimul": "жебур",
          "ID": "24",
          "seq_1_base": "жеб",
          "seq_1_c_inv": "ур",
          "seq_1_c_unmean": "ик",
          "seq_1_c_dis1": "уг",
          "seq_1_c_dis2": "ин",
          "seq_1_ipm": "565",
          "seq_1_answers_seq": "124",
          "seq_2_base": "нам",
          "seq_2_c_inv": "ор",
          "seq_2_c_unmean": "од",
          "seq_2_c_dis1": "от",
          "seq_2_c_dis2": "ог",
          "seq_2_ipm": "1577",
          "seq_2_answers_seq": "134",
          "seq_3_base": "тов",
          "seq_3_c_inv": "иж",
          "seq_3_c_unmean": "ик",
          "seq_3_c_dis1": "ин",
          "seq_3_c_dis2": "иг",
          "seq_3_ipm": "656",
          "seq_3_answers_seq": "134",
          "seq_4_base": "киж",
          "seq_4_c_inv": "ум",
          "seq_4_c_unmean": "ас",
          "seq_4_c_dis1": "ан",
          "seq_4_c_dis2": "ут",
          "seq_4_ipm": "1247",
          "seq_4_answers_seq": "124"
        },
        {
          "seq_4_stimul": "дотем",
          "seq_3_stimul": "нозес",
          "seq_2_stimul": "жебур",
          "seq_1_stimul": "жебур",
          "ID": "25",
          "seq_1_base": "жеб",
          "seq_1_c_inv": "ур",
          "seq_1_c_unmean": "ик",
          "seq_1_c_dis1": "уг",
          "seq_1_c_dis2": "ин",
          "seq_1_ipm": "565",
          "seq_1_answers_seq": "134",
          "seq_2_base": "жеб",
          "seq_2_c_inv": "ур",
          "seq_2_c_unmean": "ик",
          "seq_2_c_dis1": "уг",
          "seq_2_c_dis2": "ин",
          "seq_2_ipm": "565",
          "seq_2_answers_seq": "423",
          "seq_3_base": "ноз",
          "seq_3_c_inv": "ес",
          "seq_3_c_unmean": "ет",
          "seq_3_c_dis1": "ем",
          "seq_3_c_dis2": "ек",
          "seq_3_ipm": "692",
          "seq_3_answers_seq": "134",
          "seq_4_base": "дот",
          "seq_4_c_inv": "ем",
          "seq_4_c_unmean": "ан",
          "seq_4_c_dis1": "ин",
          "seq_4_c_dis2": "ам",
          "seq_4_ipm": "197",
          "seq_4_answers_seq": "124"
        },
        {
          "seq_4_stimul": "нозес",
          "seq_3_stimul": "сурив",
          "seq_2_stimul": "голан",
          "seq_1_stimul": "голан",
          "ID": "26",
          "seq_1_base": "гол",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "иж",
          "seq_1_c_dis1": "ар",
          "seq_1_c_dis2": "ин",
          "seq_1_ipm": "1047",
          "seq_1_answers_seq": "423",
          "seq_2_base": "гол",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "иж",
          "seq_2_c_dis1": "ар",
          "seq_2_c_dis2": "ин",
          "seq_2_ipm": "1047",
          "seq_2_answers_seq": "423",
          "seq_3_base": "сур",
          "seq_3_c_inv": "ив",
          "seq_3_c_unmean": "оп",
          "seq_3_c_dis1": "ил",
          "seq_3_c_dis2": "од",
          "seq_3_ipm": "1065",
          "seq_3_answers_seq": "423",
          "seq_4_base": "ноз",
          "seq_4_c_inv": "ес",
          "seq_4_c_unmean": "ет",
          "seq_4_c_dis1": "ем",
          "seq_4_c_dis2": "ек",
          "seq_4_ipm": "692",
          "seq_4_answers_seq": "134"
        },
        {
          "seq_4_stimul": "гопас",
          "seq_3_stimul": "телиб",
          "seq_2_stimul": "робан",
          "seq_1_stimul": "робан",
          "ID": "27",
          "seq_1_base": "роб",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "ет",
          "seq_1_c_dis1": "аг",
          "seq_1_c_dis2": "ен",
          "seq_1_ipm": "535",
          "seq_1_answers_seq": "423",
          "seq_2_base": "роб",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "ет",
          "seq_2_c_dis1": "аг",
          "seq_2_c_dis2": "ен",
          "seq_2_ipm": "535",
          "seq_2_answers_seq": "134",
          "seq_3_base": "тел",
          "seq_3_c_inv": "иб",
          "seq_3_c_unmean": "ус",
          "seq_3_c_dis1": "ип",
          "seq_3_c_dis2": "уп",
          "seq_3_ipm": "754",
          "seq_3_answers_seq": "123",
          "seq_4_base": "гоп",
          "seq_4_c_inv": "ас",
          "seq_4_c_unmean": "ет",
          "seq_4_c_dis1": "ал",
          "seq_4_c_dis2": "ед",
          "seq_4_ipm": "62",
          "seq_4_answers_seq": "423"
        },
        {
          "seq_4_stimul": "товиж",
          "seq_3_stimul": "дотем",
          "seq_2_stimul": "доран",
          "seq_1_stimul": "доран",
          "ID": "28",
          "seq_1_base": "дор",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "ем",
          "seq_1_c_dis1": "ен",
          "seq_1_c_dis2": "аг",
          "seq_1_ipm": "3856",
          "seq_1_answers_seq": "123",
          "seq_2_base": "дор",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "ем",
          "seq_2_c_dis1": "ен",
          "seq_2_c_dis2": "аг",
          "seq_2_ipm": "3856",
          "seq_2_answers_seq": "134",
          "seq_3_base": "дот",
          "seq_3_c_inv": "ем",
          "seq_3_c_unmean": "ан",
          "seq_3_c_dis1": "ин",
          "seq_3_c_dis2": "ам",
          "seq_3_ipm": "197",
          "seq_3_answers_seq": "234",
          "seq_4_base": "тов",
          "seq_4_c_inv": "иж",
          "seq_4_c_unmean": "ик",
          "seq_4_c_dis1": "ин",
          "seq_4_c_dis2": "иг",
          "seq_4_ipm": "656",
          "seq_4_answers_seq": "234"
        },
        {
          "seq_4_stimul": "телиб",
          "seq_3_stimul": "мижер",
          "seq_2_stimul": "телоп",
          "seq_1_stimul": "телоп",
          "ID": "29",
          "seq_1_base": "тел",
          "seq_1_c_inv": "оп",
          "seq_1_c_unmean": "ун",
          "seq_1_c_dis1": "од",
          "seq_1_c_dis2": "уд",
          "seq_1_ipm": "665",
          "seq_1_answers_seq": "134",
          "seq_2_base": "тел",
          "seq_2_c_inv": "оп",
          "seq_2_c_unmean": "ун",
          "seq_2_c_dis1": "од",
          "seq_2_c_dis2": "уд",
          "seq_2_ipm": "665",
          "seq_2_answers_seq": "123",
          "seq_3_base": "миж",
          "seq_3_c_inv": "ер",
          "seq_3_c_unmean": "ед",
          "seq_3_c_dis1": "ен",
          "seq_3_c_dis2": "ет",
          "seq_3_ipm": "1067",
          "seq_3_answers_seq": "423",
          "seq_4_base": "тел",
          "seq_4_c_inv": "иб",
          "seq_4_c_unmean": "ус",
          "seq_4_c_dis1": "ип",
          "seq_4_c_dis2": "уп",
          "seq_4_ipm": "754",
          "seq_4_answers_seq": "423"
        },
        {
          "seq_4_stimul": "мижер",
          "seq_3_stimul": "гопас",
          "seq_2_stimul": "намор",
          "seq_1_stimul": "намор",
          "ID": "30",
          "seq_1_base": "нам",
          "seq_1_c_inv": "ор",
          "seq_1_c_unmean": "од",
          "seq_1_c_dis1": "от",
          "seq_1_c_dis2": "ог",
          "seq_1_ipm": "1577",
          "seq_1_answers_seq": "423",
          "seq_2_base": "нам",
          "seq_2_c_inv": "ор",
          "seq_2_c_unmean": "од",
          "seq_2_c_dis1": "от",
          "seq_2_c_dis2": "ог",
          "seq_2_ipm": "1577",
          "seq_2_answers_seq": "234",
          "seq_3_base": "гоп",
          "seq_3_c_inv": "ас",
          "seq_3_c_unmean": "ет",
          "seq_3_c_dis1": "ал",
          "seq_3_c_dis2": "ед",
          "seq_3_ipm": "62",
          "seq_3_answers_seq": "134",
          "seq_4_base": "миж",
          "seq_4_c_inv": "ер",
          "seq_4_c_unmean": "ед",
          "seq_4_c_dis1": "ен",
          "seq_4_c_dis2": "ет",
          "seq_4_ipm": "1067",
          "seq_4_answers_seq": "134"
        },
        {
          "seq_4_stimul": "кижум",
          "seq_3_stimul": "кижум",
          "seq_2_stimul": "косеп",
          "seq_1_stimul": "косеп",
          "ID": "31",
          "seq_1_base": "кос",
          "seq_1_c_inv": "еп",
          "seq_1_c_unmean": "ед",
          "seq_1_c_dis1": "ад",
          "seq_1_c_dis2": "ен",
          "seq_1_ipm": "553",
          "seq_1_answers_seq": "423",
          "seq_2_base": "кос",
          "seq_2_c_inv": "еп",
          "seq_2_c_unmean": "ед",
          "seq_2_c_dis1": "ад",
          "seq_2_c_dis2": "ен",
          "seq_2_ipm": "553",
          "seq_2_answers_seq": "124",
          "seq_3_base": "киж",
          "seq_3_c_inv": "ум",
          "seq_3_c_unmean": "ас",
          "seq_3_c_dis1": "ан",
          "seq_3_c_dis2": "ут",
          "seq_3_ipm": "1247",
          "seq_3_answers_seq": "124",
          "seq_4_base": "киж",
          "seq_4_c_inv": "ум",
          "seq_4_c_unmean": "ас",
          "seq_4_c_dis1": "ан",
          "seq_4_c_dis2": "ут",
          "seq_4_ipm": "1247",
          "seq_4_answers_seq": "234"
        },
        {
          "seq_4_stimul": "сурив",
          "seq_3_stimul": "товиж",
          "seq_2_stimul": "тевос",
          "seq_1_stimul": "тевос",
          "ID": "32",
          "seq_1_base": "тев",
          "seq_1_c_inv": "ос",
          "seq_1_c_unmean": "ор",
          "seq_1_c_dis1": "ог",
          "seq_1_c_dis2": "ол",
          "seq_1_ipm": "2455",
          "seq_1_answers_seq": "134",
          "seq_2_base": "тев",
          "seq_2_c_inv": "ос",
          "seq_2_c_unmean": "ор",
          "seq_2_c_dis1": "ог",
          "seq_2_c_dis2": "ол",
          "seq_2_ipm": "2455",
          "seq_2_answers_seq": "234",
          "seq_3_base": "тов",
          "seq_3_c_inv": "иж",
          "seq_3_c_unmean": "ик",
          "seq_3_c_dis1": "ин",
          "seq_3_c_dis2": "иг",
          "seq_3_ipm": "656",
          "seq_3_answers_seq": "234",
          "seq_4_base": "сур",
          "seq_4_c_inv": "ив",
          "seq_4_c_unmean": "оп",
          "seq_4_c_dis1": "ил",
          "seq_4_c_dis2": "од",
          "seq_4_ipm": "1065",
          "seq_4_answers_seq": "234"
        },
        {
          "seq_4_stimul": "сурив",
          "seq_3_stimul": "нозес",
          "seq_2_stimul": "намор",
          "seq_1_stimul": "косеп",
          "ID": "33",
          "seq_1_base": "кос",
          "seq_1_c_inv": "еп",
          "seq_1_c_unmean": "ед",
          "seq_1_c_dis1": "ад",
          "seq_1_c_dis2": "ен",
          "seq_1_ipm": "553",
          "seq_1_answers_seq": "134",
          "seq_2_base": "нам",
          "seq_2_c_inv": "ор",
          "seq_2_c_unmean": "од",
          "seq_2_c_dis1": "от",
          "seq_2_c_dis2": "ог",
          "seq_2_ipm": "1577",
          "seq_2_answers_seq": "124",
          "seq_3_base": "ноз",
          "seq_3_c_inv": "ес",
          "seq_3_c_unmean": "ет",
          "seq_3_c_dis1": "ем",
          "seq_3_c_dis2": "ек",
          "seq_3_ipm": "692",
          "seq_3_answers_seq": "234",
          "seq_4_base": "сур",
          "seq_4_c_inv": "ив",
          "seq_4_c_unmean": "оп",
          "seq_4_c_dis1": "ил",
          "seq_4_c_dis2": "од",
          "seq_4_ipm": "1065",
          "seq_4_answers_seq": "423"
        },
        {
          "seq_4_stimul": "мижер",
          "seq_3_stimul": "дотем",
          "seq_2_stimul": "робан",
          "seq_1_stimul": "телоп",
          "ID": "34",
          "seq_1_base": "тел",
          "seq_1_c_inv": "оп",
          "seq_1_c_unmean": "ун",
          "seq_1_c_dis1": "од",
          "seq_1_c_dis2": "уд",
          "seq_1_ipm": "665",
          "seq_1_answers_seq": "124",
          "seq_2_base": "роб",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "ет",
          "seq_2_c_dis1": "аг",
          "seq_2_c_dis2": "ен",
          "seq_2_ipm": "535",
          "seq_2_answers_seq": "234",
          "seq_3_base": "дот",
          "seq_3_c_inv": "ем",
          "seq_3_c_unmean": "ан",
          "seq_3_c_dis1": "ин",
          "seq_3_c_dis2": "ам",
          "seq_3_ipm": "197",
          "seq_3_answers_seq": "134",
          "seq_4_base": "миж",
          "seq_4_c_inv": "ер",
          "seq_4_c_unmean": "ед",
          "seq_4_c_dis1": "ен",
          "seq_4_c_dis2": "ет",
          "seq_4_ipm": "1067",
          "seq_4_answers_seq": "234"
        },
        {
          "seq_4_stimul": "нозес",
          "seq_3_stimul": "мижер",
          "seq_2_stimul": "телоп",
          "seq_1_stimul": "доран",
          "ID": "35",
          "seq_1_base": "дор",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "ем",
          "seq_1_c_dis1": "ен",
          "seq_1_c_dis2": "аг",
          "seq_1_ipm": "3856",
          "seq_1_answers_seq": "423",
          "seq_2_base": "тел",
          "seq_2_c_inv": "оп",
          "seq_2_c_unmean": "ун",
          "seq_2_c_dis1": "од",
          "seq_2_c_dis2": "уд",
          "seq_2_ipm": "665",
          "seq_2_answers_seq": "423",
          "seq_3_base": "миж",
          "seq_3_c_inv": "ер",
          "seq_3_c_unmean": "ед",
          "seq_3_c_dis1": "ен",
          "seq_3_c_dis2": "ет",
          "seq_3_ipm": "1067",
          "seq_3_answers_seq": "134",
          "seq_4_base": "ноз",
          "seq_4_c_inv": "ес",
          "seq_4_c_unmean": "ет",
          "seq_4_c_dis1": "ем",
          "seq_4_c_dis2": "ек",
          "seq_4_ipm": "692",
          "seq_4_answers_seq": "124"
        },
        {
          "seq_4_stimul": "гопас",
          "seq_3_stimul": "кижум",
          "seq_2_stimul": "косеп",
          "seq_1_stimul": "голан",
          "ID": "36",
          "seq_1_base": "гол",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "иж",
          "seq_1_c_dis1": "ар",
          "seq_1_c_dis2": "ин",
          "seq_1_ipm": "1047",
          "seq_1_answers_seq": "134",
          "seq_2_base": "кос",
          "seq_2_c_inv": "еп",
          "seq_2_c_unmean": "ед",
          "seq_2_c_dis1": "ад",
          "seq_2_c_dis2": "ен",
          "seq_2_ipm": "553",
          "seq_2_answers_seq": "123",
          "seq_3_base": "киж",
          "seq_3_c_inv": "ум",
          "seq_3_c_unmean": "ас",
          "seq_3_c_dis1": "ан",
          "seq_3_c_dis2": "ут",
          "seq_3_ipm": "1247",
          "seq_3_answers_seq": "423",
          "seq_4_base": "гоп",
          "seq_4_c_inv": "ас",
          "seq_4_c_unmean": "ет",
          "seq_4_c_dis1": "ал",
          "seq_4_c_dis2": "ед",
          "seq_4_ipm": "62",
          "seq_4_answers_seq": "124"
        },
        {
          "seq_4_stimul": "дотем",
          "seq_3_stimul": "сурив",
          "seq_2_stimul": "доран",
          "seq_1_stimul": "тевос",
          "ID": "37",
          "seq_1_base": "тев",
          "seq_1_c_inv": "ос",
          "seq_1_c_unmean": "ор",
          "seq_1_c_dis1": "ог",
          "seq_1_c_dis2": "ол",
          "seq_1_ipm": "2455",
          "seq_1_answers_seq": "124",
          "seq_2_base": "дор",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "ем",
          "seq_2_c_dis1": "ен",
          "seq_2_c_dis2": "аг",
          "seq_2_ipm": "3856",
          "seq_2_answers_seq": "124",
          "seq_3_base": "сур",
          "seq_3_c_inv": "ив",
          "seq_3_c_unmean": "оп",
          "seq_3_c_dis1": "ил",
          "seq_3_c_dis2": "од",
          "seq_3_ipm": "1065",
          "seq_3_answers_seq": "134",
          "seq_4_base": "дот",
          "seq_4_c_inv": "ем",
          "seq_4_c_unmean": "ан",
          "seq_4_c_dis1": "ин",
          "seq_4_c_dis2": "ам",
          "seq_4_ipm": "197",
          "seq_4_answers_seq": "123"
        },
        {
          "seq_4_stimul": "товиж",
          "seq_3_stimul": "телиб",
          "seq_2_stimul": "голан",
          "seq_1_stimul": "робан",
          "ID": "38",
          "seq_1_base": "роб",
          "seq_1_c_inv": "ан",
          "seq_1_c_unmean": "ет",
          "seq_1_c_dis1": "аг",
          "seq_1_c_dis2": "ен",
          "seq_1_ipm": "535",
          "seq_1_answers_seq": "123",
          "seq_2_base": "гол",
          "seq_2_c_inv": "ан",
          "seq_2_c_unmean": "иж",
          "seq_2_c_dis1": "ар",
          "seq_2_c_dis2": "ин",
          "seq_2_ipm": "1047",
          "seq_2_answers_seq": "134",
          "seq_3_base": "тел",
          "seq_3_c_inv": "иб",
          "seq_3_c_unmean": "ус",
          "seq_3_c_dis1": "ип",
          "seq_3_c_dis2": "уп",
          "seq_3_ipm": "754",
          "seq_3_answers_seq": "423",
          "seq_4_base": "тов",
          "seq_4_c_inv": "иж",
          "seq_4_c_unmean": "ик",
          "seq_4_c_dis1": "ин",
          "seq_4_c_dis2": "иг",
          "seq_4_ipm": "656",
          "seq_4_answers_seq": "124"
        },
        {
          "seq_4_stimul": "телиб",
          "seq_3_stimul": "товиж",
          "seq_2_stimul": "тевос",
          "seq_1_stimul": "жебур",
          "ID": "39",
          "seq_1_base": "жеб",
          "seq_1_c_inv": "ур",
          "seq_1_c_unmean": "ик",
          "seq_1_c_dis1": "уг",
          "seq_1_c_dis2": "ин",
          "seq_1_ipm": "565",
          "seq_1_answers_seq": "123",
          "seq_2_base": "тев",
          "seq_2_c_inv": "ос",
          "seq_2_c_unmean": "ор",
          "seq_2_c_dis1": "ог",
          "seq_2_c_dis2": "ол",
          "seq_2_ipm": "2455",
          "seq_2_answers_seq": "423",
          "seq_3_base": "тов",
          "seq_3_c_inv": "иж",
          "seq_3_c_unmean": "ик",
          "seq_3_c_dis1": "ин",
          "seq_3_c_dis2": "иг",
          "seq_3_ipm": "656",
          "seq_3_answers_seq": "423",
          "seq_4_base": "тел",
          "seq_4_c_inv": "иб",
          "seq_4_c_unmean": "ус",
          "seq_4_c_dis1": "ип",
          "seq_4_c_dis2": "уп",
          "seq_4_ipm": "754",
          "seq_4_answers_seq": "134"
        },
        {
          "seq_4_stimul": "кижум",
          "seq_3_stimul": "гопас",
          "seq_2_stimul": "жебур",
          "seq_1_stimul": "намор",
          "ID": "40",
          "seq_1_base": "нам",
          "seq_1_c_inv": "ор",
          "seq_1_c_unmean": "од",
          "seq_1_c_dis1": "от",
          "seq_1_c_dis2": "ог",
          "seq_1_ipm": "1577",
          "seq_1_answers_seq": "123",
          "seq_2_base": "жеб",
          "seq_2_c_inv": "ур",
          "seq_2_c_unmean": "ик",
          "seq_2_c_dis1": "уг",
          "seq_2_c_dis2": "ин",
          "seq_2_ipm": "565",
          "seq_2_answers_seq": "134",
          "seq_3_base": "гоп",
          "seq_3_c_inv": "ас",
          "seq_3_c_unmean": "ет",
          "seq_3_c_dis1": "ал",
          "seq_3_c_dis2": "ед",
          "seq_3_ipm": "62",
          "seq_3_answers_seq": "124",
          "seq_4_base": "киж",
          "seq_4_c_inv": "ум",
          "seq_4_c_unmean": "ас",
          "seq_4_c_dis1": "ан",
          "seq_4_c_dis2": "ут",
          "seq_4_ipm": "1247",
          "seq_4_answers_seq": "123"
        }
      ],
      "sample": {
        "mode": "sequential",
        "n": ""
      },
      "files": {},
      "responses": {
        "": ""
      },
      "parameters": {},
      "messageHandlers": {
        "before:prepare": function anonymous(
) {
console.log(stimules.length)
}
      },
      "title": "Узнавание",
      "indexParameter": "counter",
      "tardy": true,
      "shuffleGroups": [],
      "template": {
        "type": "lab.flow.Sequence",
        "files": {},
        "responses": {
          "": ""
        },
        "parameters": {},
        "messageHandlers": {},
        "title": "Последовательность",
        "content": [
          {
            "type": "lab.canvas.Screen",
            "content": [
              {
                "type": "i-text",
                "left": 0,
                "top": 0,
                "angle": 0,
                "width": 18.69,
                "height": 36.16,
                "stroke": "#000000",
                "strokeWidth": 1,
                "fill": "#ffffff",
                "text": "+",
                "fontStyle": "normal",
                "fontWeight": "normal",
                "fontSize": 32,
                "fontFamily": "sans-serif",
                "lineHeight": 1.16,
                "textAlign": "center"
              }
            ],
            "viewport": [
              800,
              600
            ],
            "files": {},
            "responses": {
              "": ""
            },
            "parameters": {},
            "messageHandlers": {},
            "title": "Фиксационный крест",
            "timeout": "300"
          },
          {
            "type": "lab.html.Page",
            "items": [
              {
                "required": true,
                "type": "html",
                "content": "\u003Ccenter\u003E\r\n\u003Cdiv class=\"detect_card\" style=\"height: 225px\"\u003E\r\nВыберите вариант\r\n\u003Chr\u003E\r\n\u003Ccenter style=\"font-size: 20px;\"\u003E${ parameters['seq_' + sequence + '_base'] }__\r\n  \u003Cdiv\u003E\r\n    ${ get_sequence_answer(parameters) }\r\n  \u003C\u002Fdiv\u003E\r\n\u003C\u002Fcenter\u003E\r\n\u003Chr\u003E\r\n\u003Cdiv id=\"progressbarcontainer\"\u003E\r\n    \u003Cdiv id=\"progressbar\" style=\"width: ${ parseInt(parameters.counter) \u002F 40 * 100 }%\"\u003E\r\n    \u003C\u002Fdiv\u003E\r\n\u003C\u002Fdiv\u003E\r\n\u003C\u002Fdiv\u003E\r\n\u003Cbr\u003E\r\n\u003Cbutton type=\"submit\" class=\"custom-btn btn-3\"\u003E\u003Cspan\u003EОтветить\u003C\u002Fspan\u003E\u003C\u002Fbutton\u003E\r\n\u003Ccenter\u003E\r\n",
                "name": ""
              }
            ],
            "scrollTop": true,
            "submitButtonText": "Continue →",
            "submitButtonPosition": "hidden",
            "files": {},
            "responses": {},
            "parameters": {},
            "messageHandlers": {
              "before:prepare": function anonymous(
) {
window.generate_radio = function(text, id) {
    return(`<input type="radio" id="slog_` + id + `" name="slog_answer" value="` +  text  + `"/>
    <label for="slog_` + id + `">` + text  + `</label><br>`)
}

window.get_sequence_answer = function(parameters) {
  answers_seq = parameters['seq_' + this.sequence + '_answers_seq'].toString()
  let dict = {
    "4": "_c_dis2", 
    "3": "_c_dis1",
    "2": "_c_unmean",
    "1": "_c_inv",
  }
  
  return(
    generate_radio(parameters['seq_' + this.sequence + dict[answers_seq[0]]], 1) +
    generate_radio(parameters['seq_' + this.sequence + dict[answers_seq[1]]], 2) + 
    generate_radio(parameters['seq_' + this.sequence + dict[answers_seq[2]]], 3)
  )
}

}
            },
            "title": "ответы (код)",
            "tardy": true
          }
        ]
      }
    },
    {
      "type": "lab.html.Page",
      "items": [
        {
          "required": true,
          "type": "html",
          "content": "\u003Ccenter\u003E\r\n\u003Cdiv class=\"detect_card\" style=\"text-align: left; width: 460px; height: 250px\"\u003E\r\nВ настоящем исследовании наряду с бессмысленными буквенными рядами были использованы зашифрованные \u003Cb\u003Eслова-инверсии\u003C\u002Fb\u003E (слова, написанные наоборот)\u003Cp\u003EПример слова-инверсии: \u003Cb style=\"color:rgba(69, 192, 250, 1)\"\u003Eакызум – музыка.\u003C\u002Fb\u003E\u003Cp\u003E\r\n\u003Ccenter\u003E\u003Cbutton type=\"submit\" class=\"custom-btn btn-3\"\u003E\u003Cspan\u003EДалее\u003C\u002Fspan\u003E\u003C\u002Fbutton\u003E\u003C\u002Fcenter\u003E\r\n\u003C\u002Fdiv\u003E\r\n\u003C\u002Fcenter\u003E\r\n",
          "name": ""
        }
      ],
      "scrollTop": true,
      "submitButtonText": "Continue →",
      "submitButtonPosition": "hidden",
      "files": {},
      "responses": {
        "": ""
      },
      "parameters": {},
      "messageHandlers": {},
      "title": "Инструкция_3"
    },
    {
      "type": "lab.html.Page",
      "items": [
        {
          "required": true,
          "type": "html",
          "content": "\u003Ccenter\u003E\r\n\u003Cdiv class=\"detect_card\" style=\"text-align: left; width: 430px; height: 450px\"\u003E\r\nСкажите, заметили ли Вы, что некоторые из предъявленных Вам стимулов в обратном прочтении образуют реальные слова?\u003Cbr\u003E\r\n\u003Cselect class=\"custom-btn custom_select\" name=\"inversion\"\u003E\r\n  \u003Coption value=\"yes\" selected\u003EДа\u003C\u002Foption\u003E\r\n  \u003Coption value=\"no\"\u003EНет\u003C\u002Foption\u003E\r\n\u003C\u002Fselect\u003E\r\n\u003Cp\u003EЕсли да, будьте добры, постарайтесь написать через запятую те зашифрованные слова, которые Вам удалось заметить.\u003Cp\u003E\r\n\u003Ctextarea name=\"words\" cols=\"40\" rows=\"3\"\u003E\u003C\u002Ftextarea\u003E\u003Cp\u003E\r\n\u003Ccenter\u003E\u003Cbutton type=\"submit\" class=\"custom-btn btn-3\"\u003E\u003Cspan\u003EДалее\u003C\u002Fspan\u003E\u003C\u002Fbutton\u003E\u003C\u002Fcenter\u003E\r\n\u003C\u002Fdiv\u003E\r\n\u003C\u002Fcenter\u003E\r\n",
          "name": ""
        }
      ],
      "scrollTop": true,
      "submitButtonText": "Continue →",
      "submitButtonPosition": "hidden",
      "files": {},
      "responses": {
        "": ""
      },
      "parameters": {},
      "messageHandlers": {
        "end": function anonymous(
) {
window.inversion = this.data.inversion
window.words = this.data.words

}
      },
      "title": "Проверка_на_бессознательность (скрипт)"
    },
    {
      "type": "lab.html.Page",
      "items": [
        {
          "type": "text",
          "content": "\u003Ccenter\u003E\n\u003Cdiv class=\"detect_card\" style=\"text-align: left; width: 500px; height:  200px\"\u003E\n\u003Ch3\u003EБлагодарю за уделенное время!\u003C\u002Fh3\u003EВаши ответы действительно важны для нас. \u003Cbr\u003EСегодня Вы внесли свой посильный вклад в науку!\n\u003C\u002Fdiv\u003E\n\u003C\u002Fcenter\u003E"
        }
      ],
      "scrollTop": true,
      "submitButtonText": "Continue →",
      "submitButtonPosition": "hidden",
      "files": {},
      "responses": {
        "": ""
      },
      "parameters": {},
      "messageHandlers": {
        "run": function anonymous(
) {
let data = this.options.datastore.data,
    results = [],
    _anwsers = ["стимулы", "ответы (код)"];
    for(ind in data) {
			for(ind2 in _anwsers) 
				if(data[ind].sender == _anwsers[ind2]) {
					let response = data[ind];
					console.log(response)
					results.push({
						'sex': sex,
						'age': age,
						'email': email,
						'sequence': sequence,
						'group': sequence <= 2? 1 : 2,
						'rtime': response.duration,
						'slog_answer': response.sender == _anwsers[0]? "" : response.response,
						'type': response['seq_' + sequence + '_type'],
						'stimul': response['seq_' + sequence + '_stimul'],
						'ipm': response['seq_' + sequence + '_ipm'],
						'base':	response['seq_' + sequence + '_base'],
						'c_inv': response['seq_' + sequence + '_c_inv'],
						'c_unmean':	 response['seq_' + sequence + '_c_unmean'],
						'c_dis1':	response['seq_' + sequence + '_c_dis1'],
						'c_dis2': response['seq_' + sequence + '_c_dis2'],
						'answers_seq': response['seq_' + sequence + '_answers_seq'],
						'stage': (response.sender == "ответы" ? 2 : 1),
						'inversion': inversion,
						'words': words,
						'counter': response.counter
					})
				}
	}

console.log(results)

let xmlhttp = new XMLHttpRequest(),
    	slice_formdata = new FormData(),
    	the_url = "https://script.google.com/macros/s/AKfycbx4B6GHjjlRQW7xEOZIRvxmXNyrh1LBuSRff1yH6o28uQ_yQDffHreKlddO34za_B57/exec";
    
slice_formdata.append('data', JSON.stringify(results));

for(ind in results)     	
	slice_formdata.append(ind, JSON.stringify(results[ind]))

xmlhttp.open("POST", the_url, false);
xmlhttp.send(slice_formdata);

		
}
      },
      "title": "Финал (скрипт)",
      "timeout": "100"
    }
  ]
})

// Let's go!
study.run()